### ISSUE TITLE
How can I use this package?

### ISSUE THREAD

**Issue by aminya** [EmbeddedEnterprises/cmake-ts#9]
I wanted to use this package, but I have a couple of questions:
- I could not find any examples in the repository. How should I write my Cmake file? and what is its relation with my Cmake-ts configuration? 
- Does Cmake-TS have a CLI tool that I need to call during building or installation?
- How can I build for both Release and Debug without changing package.json?
- Do you plan to add tests for this package?
- Is there a tool like `prebuildify` or `prebuild-install` for this package? 
- Does it support `N-API`? The configuration in the readme uses NAN.

I was going to start a similar project, but I saw this repository. I think it has very good potential, and if we can solve the above questions, I will start to use it for a couple of native packages. I can help with the development of this repository!

**Comment by martin31821** [comment]
That's a good point, i'll see whether I can add a full fledged example. 

- This package comes as a CLI tool, which needs to be invoked during the build step of a native addon. 
- Tests were planned, however not a priority right now. 
- No prebuildify is currently here.
- We only support one build type at a time, what's your use case for having both?
- We only support NAN at this time.

**Comment by aminya** [comment]
Supporting N-api is very important. Without that, I cannot use CMake-ts. It is highly recommended to use N-api instead of NAN.

**Comment by martin31821** [comment]
Agree on the first points, I like the build type override. 

Unfortunately, nan is a bit hardwired at the moment, that's something we need to make more pluggable. 
I agree to add n-api support, but I don't have an example library using n-api.

**Comment by aminya** [comment]
I have an N-API library called Zadeh. I wanted to transfer this to Cmake-ts. 

https://github.com/atom-community/zadeh

**Comment by aminya** [comment]
I added NAPI support in #14. Although I have not tested it yet. If you can first try your NAN package with this branch, it would be great. Then, if it was working, I will go ahead and transfer Zadeh to Cmake-ts.

**Comment by martin31821** [comment]
I'll try it, looks good at first sight.

**Comment by aminya** [comment]
@martin31821 Any news? Were you able to test #14? 

If you can add one of the Cmake file examples you showed me in our meeting to the repository, it would be awesome. This also helps me to continue the development of this repository.

**Comment by aminya** [comment]
@martin31821 could you give me access to this repository?

**Comment by aminya** [comment]
A year later, I am still searching for a usage example.

**Comment by MrTob** [comment]
same here, pls help me. i want to migrate from cmake-js to cmake-ts
how to include the built ".node" file into an angular electron app?

**Comment by aminya** [comment]
Hey @martin31821, I am still interested in making cmake-ts a successful project. I see that the project is unmaintained. Would you be interested in adding me as a maintainer?

**Comment by martin31821** [comment]
Hi,

I have, as of now, unfortunately not the energy or time to invest more into this
project. If you'd like to take over, I can transfer the project to you.

Best

**Comment by aminya** [comment]
@martin31821 Sure, I'd be happy to help maintain this package. There's no need to transfer. I can continue the progress here if you send me an invitation to the repository.

**Comment by martin31821** [comment]
@aminya i've invited you for maintainer access - I'll close this.

**Comment by aminya** [comment]
Thanks for the invitation! I will start merging the patches.
